// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcxlnxnkrvdgqezikxgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjeGxueG5rcnZkZ3FlemlreGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODA1ODMsImV4cCI6MjA2ODc1NjU4M30.h_hAE2g4YLWkwRLr8S4BWRgx9A0jxL1g4z9IQQznegY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});